server:
  port: 8082

spring:
  application:
    name: booking-service
  config:
    import: configserver:http://localhost:8888

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      movieService:
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s